### ISSUE TITLE
Add flag(s) to make model non-browsable, transient

### ISSUE THREAD

**Issue by ewencp** [sirikata/sirikata-cdn#3]
Content which is dynamically generated, like aggregate meshes from the space server, are likely transient and almost certainly not usable by regular users. We need some flags which disable displaying these models when browsing the CDN (in a browser or by API). This same flag or another might also indicate that the data is transient -- it'll likely become invalid.

**Comment by jterrace** [comment]
File that are not added to NameTimestampIndex are essentially invisible on the site, so aggregates will just not be added.

**Comment by ewencp** [comment]
Can you clarify what you mean here? NameTimestampIndex sounds like something internal. Is there some flag that controls whether it gets added to that index?

**Comment by jterrace** [comment]
Yeah, it's internal. There's no flag right now, but it would be easy to add one. I was just saying that there doesn't need to be a separate mechanism for making something invisible - just not adding it to the index makes it invisible.

**Comment by ewencp** [comment]
Now that the space server can upload aggregates to the CDN, exposing this via the API is pretty important -- aggregates quickly fill up many pages of results when browsing the site.

**Comment by jterrace** [comment]
This should be working now
