### ISSUE TITLE
Allow API uploads to specify URLs for assets (e.g. textures)

### ISSUE THREAD

**Issue by ewencp** [sirikata/sirikata-cdn#6]
These could be restricted to URLs on the same CDN, but this is pretty important for making aggregate uploads efficient since textures can be a large fraction of the content and aggregates are mostly just reusing them.

**Comment by jterrace** [comment]
dff61866f5ffb16a17194009f923ca079e87a030 adds support for specifying existing textures when uploading ephemeral files
